/* Auto-generated by cbindgen. DO NOT EDIT manually. Regenerated on build. */

#ifndef UVIE_H
#define UVIE_H

#include <stddef.h>
#include <stdint.h>

/**
 * Opaque handle to the engine. C code only ever holds a pointer to this type;
 * the fields are intentionally not part of the C ABI.
 */
typedef struct UvieEngine UvieEngine;

typedef struct UvieReplayEngine UvieReplayEngine;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

UvieEngine *uvie_engine_new(void);

void uvie_engine_free(UvieEngine *engine);

void uvie_engine_clear(UvieEngine *engine);

void uvie_engine_commit(UvieEngine *engine);

void uvie_engine_set_input_method(UvieEngine *engine, int method);

int uvie_engine_get_input_method(const UvieEngine *engine);

void uvie_engine_set_quick_start(UvieEngine *engine, int enabled);

void uvie_engine_set_quick_telex(UvieEngine *engine, int enabled);

void uvie_engine_set_modern_orthography(UvieEngine *engine, int enabled);

size_t uvie_engine_backspace(UvieEngine *engine, char *out_buf, size_t out_len);

int uvie_engine_is_composing(const UvieEngine *engine);

int uvie_engine_is_empty(const UvieEngine *engine);

size_t uvie_engine_current_output(const UvieEngine *engine, char *out_buf, size_t out_len);

size_t uvie_engine_current_composing(const UvieEngine *engine, char *out_buf, size_t out_len);

size_t uvie_engine_committed_text(const UvieEngine *engine, char *out_buf, size_t out_len);

size_t uvie_engine_feed_utf8(UvieEngine *engine, uint8_t ch, char *out_buf, size_t out_len);

UvieReplayEngine *uvie_replay_new(void);

void uvie_replay_free(UvieReplayEngine *engine);

void uvie_replay_set_input_method(UvieReplayEngine *engine, int method);

void uvie_replay_set_quick_start(UvieReplayEngine *engine, int enabled);

void uvie_replay_set_quick_telex(UvieReplayEngine *engine, int enabled);

void uvie_replay_set_modern_orthography(UvieReplayEngine *engine, int enabled);

/**
 * Feed a single UTF-8 character.
 * Returns the number of backspaces the caller must send,
 * and writes the new output string into `out_buf`.
 */
size_t uvie_replay_feed(UvieReplayEngine *engine, char ch, char *out_buf, size_t out_len);

/**
 * Handle backspace.
 * Returns backspace count, writes new output into `out_buf`.
 */
size_t uvie_replay_backspace(UvieReplayEngine *engine, char *out_buf, size_t out_len);

/**
 * Commit the current word (call on space / punctuation).
 * Returns backspace count (usually 0), clears output buffer.
 */
size_t uvie_replay_commit(UvieReplayEngine *engine, char *out_buf, size_t out_len);

void uvie_replay_reset(UvieReplayEngine *engine);

int uvie_replay_is_composing(const UvieReplayEngine *engine);

/**
 * Get the accumulated committed text (auto-committed syllables).
 * Returns byte count of written string (excluding null terminator).
 */
size_t uvie_replay_committed_text(const UvieReplayEngine *engine, char *out_buf, size_t out_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* UVIE_H */
